---
title: "subsample 36 years when life expectancy is increasing in a certain time range(increase only in the first 100 years)"
output: html_document
---
We subsample 36 years under the third simulation scenario that the life expectancy has been rising up to the 100 years and stablize without further improvement.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path="../figs/")
```

```{r loadpackage,ehco=FALSE}
library(simsurv)
library(dplyr)
library(ggplot2)
library(reshape)
source("weibull_function.R")
```

```{r scenario3 36yrs,echo=TRUE}
set.seed(1)
N=500
#every individual was born each year during the 500 years
Year.of.birth<-seq(0,N-1,1)
mean.all<-0
median.all<-0
#life expectancy stop rising at the 480th year
start=1
end=480
for (i in 1:1000){
#simulate survival time during 500 years
Age.of.death<-weibull_eventtime_stop(25.29704,20.8,0.05,0.05,N,start,end)
Year.of.death<-Year.of.birth+Age.of.death
survdata<-data.frame(Year.of.birth,Year.of.death,Age.of.death)
#mean and median survival time of the individuals who died between the 466th year to the 500th year(36years)
mean.all[i]=mean((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])
median.all[i]=median((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])

}
#expected mean=49.25
#simulated mean survival time:
mean(mean.all)
#expected median=44.75
#simulated median survival time:
mean(median.all)
#boxplot of means
simulation_num<-1:1000
meanmedian=data.frame(mean=mean.all,median=median.all,simulation_num)
df<-melt(meanmedian,c("simulation_num"))
true<-data.frame(variable=c("mean","median"),hline=c(49.25,44.75))
df %>% ggplot(aes(x=variable,y=value))+geom_boxplot() +geom_jitter(alpha=0.1,position = position_jitter(width = 0.3,seed=1))+xlab("mean")+ylab("value")+stat_summary(fun.y = "mean", geom = "point", colour = "#000000", size = 2)+ stat_summary(fun.y="mean", colour="#000000", geom="text", vjust=-0.7,size=4, aes( label=round(..y.., digits=1)))+geom_errorbar(data=true,aes(y=NULL,ymax=hline,ymin=hline),linetype="dashed",color=c("#0072B2","#D55E00"),position=position_dodge())+geom_text(aes(1,49.35),label="49.25",size=4,color="#0072B2")+geom_text(aes(2,44.85),label="44.75",size=4,color="#D55E00")+xlab("Statistics")+ylab("Value")+theme_bw(base_size = 18,base_family = "")
```
