---
title: "scenario_mean_median"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path="../figs/")
```

```{r loadpackage,ehco=FALSE}
library(simsurv)
source("weibull_function.R")
library(dplyr)
library(ggplot2)
```

```{r constant,include=FALSE}
mean=rep(25.3,500)
median=rep(20.8,500)
year=1:500
colors=c("Mean survival time"="#0072B2","Median survival time"="#D55E00")
df=data.frame(year,mean,median)
df %>% ggplot(aes(year)) + geom_line(aes(y=mean,x=year,color="Mean survival time")) + geom_line(aes(y=median,x=year,color = "Median survival time"))+ylim(0,30)+scale_x_continuous(breaks=c(1,465,500),labels=c("1","465","500"))+scale_color_manual(values = colors)+ylab("Value")+xlab("Year")+geom_text(aes(label=c("25.3"),x=510,y=mean),color="#0072B2",size=4.5)+geom_text(aes(label=c("20.8"),x=510,y=median),color="#D55E00",size=4.5)+labs(colour="")+theme_bw(base_size = 15,base_family = "")+theme(axis.text.x = element_text(angle = 70, hjust = 1, vjust = 0.5))
```

```{r increasing500,include=FALSE}
order=0:499
mean=25.3+0.05*order
median=20.8+0.05*order
year=1:500
colors=c("Mean survival time"="#0072B2","Median survival time"="#D55E00")
df=data.frame(year,mean,median)
df %>% ggplot(aes(year)) + geom_line(aes(y=mean,x=year,color="Mean survival time")) + geom_line(aes(y=median,x=year,color = "Median survival time"))+scale_x_continuous(breaks=c(1,465,500),labels=c("0","465","500"))+scale_color_manual(values = colors)+ylab("Value")+xlab("Year")+geom_text(aes(label=mean[1],x=-1,y=mean[1]),color="#0072B2",size=3.8)+geom_text(aes(label=median[1],x=-1,y=median[1]),color="#D55E00",size=3.8)+geom_text(aes(label=mean[500],x=510,y=mean[500]),color="#0072B2",size=3.8)+geom_text(aes(label=median[500],x=510,y=median[500]),color="#D55E00",size=3.8)+ylim(0,52)+labs(colour="")+theme_bw(base_size = 15,base_family = "")+theme(axis.text.x = element_text(angle = 70, hjust = 1, vjust = 0.5))
```

```{r increasing first 100yrs,include=FALSE}
order=c(0:479,rep(479,20))
mean=25.3+0.05*order
median=20.8+0.05*order
year=1:500
colors=c("Mean survival time"="#0072B2","Median survival time"="#D55E00")
df=data.frame(year,mean,median)
df %>% ggplot(aes(year)) + geom_line(aes(y=mean,x=year,color="Mean survival time")) + geom_line(aes(y=median,x=year,color = "Median survival time"))+scale_x_continuous(breaks=c(1,100,480,500),labels=c("1","100","480","500"))+scale_color_manual(values = colors)+ylab("Value")+xlab("Year")+geom_text(aes(label=mean[1],x=-1,y=mean[1]),color="#0072B2",size=3.8)+geom_text(aes(label=median[1],x=-1,y=median[1]),color="#D55E00",size=3.8)+geom_text(aes(label=mean[500],x=510,y=mean[500]),color="#0072B2",size=3.8)+geom_text(aes(label=median[500],x=510,y=median[500]),color="#D55E00",size=3.8)+ylim(0,51)+labs(colour="")+theme_bw(base_size = 15,base_family = "")+theme(axis.text.x = element_text(angle = 70, hjust = 1, vjust = 0.5))
```

```{r increasing last 20yrs,include=FALSE}
order=c(rep(0,480),1:20)
mean=25.3+0.5*order
median=20.8+0.5*order
year=1:500
colors=c("Mean survival time"="#0072B2","Median survival time"="#D55E00")
df=data.frame(year,mean,median)
df %>% ggplot(aes(year)) + geom_line(aes(y=mean,x=year,color="Mean survival time")) + geom_line(aes(y=median,x=year,color = "Median survival time"))+scale_x_continuous(breaks=c(1,480,500),labels=c("1","480","500"))+scale_color_manual(values = colors)+ylab("Value")+xlab("Year")+geom_text(aes(label=mean[1],x=-2,y=mean[1]),color="#0072B2",size=4.5)+geom_text(aes(label=median[1],x=-2,y=median[1]),color="#D55E00",size=4.5)+geom_text(aes(label=mean[500],x=510,y=mean[500]),color="#0072B2",size=4.5)+geom_text(aes(label=median[500],x=510,y=median[500]),color="#D55E00",size=4.5)+ylim(0,36)+labs(colour="")+theme_bw(base_size = 15,base_family = "")+theme(axis.text.x = element_text(angle = 70, hjust = 1, vjust = 0.5))
```