---
title: "subsample 36 years when life expectancy is increasing in a certain time range(increase from 1990 to 2010)"
output: html_document
---

We subsample the last 36 years under the third simulation scenario. To simulate the similar changes in life expectancy to the findings in the Lavery and Hendriksz paper, the mean and median survival time increase by 0.05 each year from the 480 year to the 500 year.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path="../figs/")
```

```{r loadpackage,ehco=FALSE}
library(simsurv)
source("weibull_function.R")
library(dplyr)
library(ggplot2)
library(reshape)
```

```{r scenario4 36yrs,echo=TRUE}
set.seed(1)
N=500
#every individual was born each year during the 500 years
Year.of.birth<-seq(0,N-1,1)
mean.all<-0
median.all<-0
mean_=25.29704
median_=20.8
meandep=0.5
mediandep=0.5
#simulate that the life expectancy is increasing during the last 21 years(1990-2010)
start=480
end=500
for (i in 1:1000){
#simulate survival time during 500 years
Age.of.death<-weibull_eventtime_stop(mean_,median_,meandep,mediandep,N,start,end)
Year.of.death<-Year.of.birth+Age.of.death
survdata<-data.frame(Year.of.birth,Year.of.death,Age.of.death)
#mean and median survival time of the individuals who died between the 465th year to the 500th year(36years)
mean.all[i]=mean((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])
median.all[i]=median((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])
}
#simulated mean survival time:
mean(mean.all)
#simulated median survival time:
mean(median.all)
#boxplot of means
meanend=mean_+meandep*(end-start)
medianend=median_+mediandep*(end-start)
simulation_num<-1:1000
meanmedian=data.frame(mean=mean.all,median=median.all,simulation_num)
df<-melt(meanmedian,c("simulation_num"))
true<-data.frame(variable=c("mean","median"),hline=c(meanend,medianend))
df %>% ggplot(aes(x=variable,y=value))+geom_boxplot() +geom_jitter(alpha=0.1,position = position_jitter(width = 0.3,seed=1))+xlab("mean")+ylab("value")+stat_summary(fun.y = "mean", geom = "point", colour = "#000000", size = 2)+ stat_summary(fun.y="mean", colour="#000000", geom="text", vjust=-0.7,size=4, aes( label=round(..y.., digits=1)))+geom_errorbar(data=true,aes(y=NULL,ymax=hline,ymin=hline),linetype="dashed",color=c("#0072B2","#D55E00"),position=position_dodge())+geom_text(aes(1,meanend-0.4),label=round(meanend,digits=2),size=4,color="#0072B2")+geom_text(aes(2,medianend-0.4),label=round(medianend,digits=2),size=4,color="#D55E00")+xlab("Statistics")+ylab("Value")+theme_bw(base_size = 18,base_family = "")
```
```
