---
title: "compile 4 scenarios"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadpackage,ehco=FALSE}
library(simsurv)
library(dplyr)
library(ggplot2)
library(reshape)
source("weibull_function.R")
```

```{r read data,include=FALSE}
survival<-read.csv("../data/M_Type_A_survival.csv")
```

Scenario 1: Constant life expectancy

```{r scenario1 36yrs,echo=FALSE}
set.seed(1)
N=500
#every individual was born each year during the 500 years
Year.of.birth<-seq(0,N-1,1)
mean.all<-0
median.all<-0
mean_=mean(survival$Age.at.death)
median_=median(survival$Age.at.death)
meandep=0
mediandep=0
for (i in 1:1000){
#simulate survival time during 500 years
Age.of.death<-weibull_eventtime(mean_,median_,meandep,mediandep,N)
Year.of.death<-Year.of.birth+Age.of.death
survdata<-data.frame(Year.of.birth,Year.of.death,Age.of.death)
#mean and median survival time of the individuals who died between the 466th year to the 500th year(36years)
mean.all[i]=mean((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])
median.all[i]=median((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])
}
#boxplot of means and medians
simulation_num<-1:1000
meanmedian=data.frame(mean=mean.all,median=median.all,simulation_num)
df<-melt(meanmedian,c("simulation_num"))
true<-data.frame(variable=c("mean","median"),hline=c(mean_,median_))
df %>% ggplot(aes(x=variable,y=value))+geom_boxplot() +geom_jitter(alpha=0.1,position = position_jitter(width = 0.3,seed=1))+stat_summary(fun.y = "mean", geom = "point", colour = "#000000", size = 2)+ stat_summary(fun.y="mean", colour="#000000", geom="text", vjust=-0.7,size=4, aes( label=round(..y.., digits=1)))+geom_errorbar(data=true,aes(y=NULL,ymax=hline,ymin=hline),linetype="dashed",color=c("#0072B2","#D55E00"),position=position_dodge())+geom_text(aes(1,mean_-0.6),label=round(mean_,digits=2),size=4,color=c("#0072B2"))+geom_text(aes(2,median_-0.6),label=round(median_,digits=2),size=4,color="#D55E00")+xlab("Statistics")+ylab("Value")+theme_bw(base_size = 18,base_family = "")
```

Senario 2: Gradually increasing life expectancy

```{r scenario2 36yrs,echo=FALSE}
set.seed(1)
N=500
#every individual was born each year during the 500 years
Year.of.birth<-seq(0,N-1,1)
mean.all<-0
median.all<-0
mean_=mean(survival$Age.at.death)
median_=median(survival$Age.at.death)
meandep=0.05
mediandep=0.05
for (i in 1:1000){
#simulate survival time during 500 years
Age.of.death<-weibull_eventtime(mean_,median_,meandep,mediandep,N)
Year.of.death<-Year.of.birth+Age.of.death
survdata<-data.frame(Year.of.birth,Year.of.death,Age.of.death)
#mean and median survival time of the individuals who died between the 466th year to the 500th year(36years)
mean.all[i]=mean((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])
median.all[i]=median((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])
}
#boxplot of means and medians
meanend=mean_+meandep*(N-1)
medianend=median_+mediandep*(N-1)
simulation_num<-1:1000
meanmedian=data.frame(mean=mean.all,median=median.all,simulation_num)
df<-melt(meanmedian,c("simulation_num"))
true<-data.frame(variable=c("mean","median"),hline=c(meanend,medianend))
df %>% ggplot(aes(x=variable,y=value))+geom_boxplot() +geom_jitter(alpha=0.1,position = position_jitter(width = 0.3,seed=1))+stat_summary(fun.y = "mean", geom = "point", colour = "#000000", size = 2)+ stat_summary(fun.y="mean", colour="#000000", geom="text", vjust=-0.7,size=4, aes( label=round(..y.., digits=1)))+geom_errorbar(data=true,aes(y=NULL,ymax=hline,ymin=hline),linetype="dashed",color=c("#0072B2","#D55E00"),position=position_dodge())+geom_text(aes(1,meanend-0.4),label=round(meanend,digits=2),size=4,color="#0072B2")+geom_text(aes(2,medianend-0.4),label=round(medianend,digits=2),size=4,color="#D55E00")+xlab("Statistics")+ylab("Value")+theme_bw(base_size = 18,base_family = "")
```

Scenario 3: Gradually increasing life expectancy that later stabilizes

```{r scenario3 36yrs,echo=FALSE}
set.seed(1)
N=500
#every individual was born each year during the 500 years
Year.of.birth<-seq(0,N-1,1)
mean.all<-0
median.all<-0
mean_=mean(survival$Age.at.death)
median_=median(survival$Age.at.death)
meandep=0.05
mediandep=0.05
#life expectancy stop rising at the 480th year
start=1
end=480
for (i in 1:1000){
#simulate survival time during 500 years
Age.of.death<-weibull_eventtime_stop(mean_,median_,meandep,mediandep,N,start,end)
Year.of.death<-Year.of.birth+Age.of.death
survdata<-data.frame(Year.of.birth,Year.of.death,Age.of.death)
#mean and median survival time of the individuals who died between the 466th year to the 500th year(36years)
mean.all[i]=mean((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])
median.all[i]=median((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])

}
#boxplot of means and medians
meanend=mean_+meandep*(end-start)
medianend=median_+mediandep*(end-start)
simulation_num<-1:1000
meanmedian=data.frame(mean=mean.all,median=median.all,simulation_num)
df<-melt(meanmedian,c("simulation_num"))
true<-data.frame(variable=c("mean","median"),hline=c(meanend,medianend))
df %>% ggplot(aes(x=variable,y=value))+geom_boxplot() +geom_jitter(alpha=0.1,position = position_jitter(width = 0.3,seed=1))+xlab("mean")+ylab("value")+stat_summary(fun.y = "mean", geom = "point", colour = "#000000", size = 2)+ stat_summary(fun.y="mean", colour="#000000", geom="text", vjust=-0.7,size=4, aes( label=round(..y.., digits=1)))+geom_errorbar(data=true,aes(y=NULL,ymax=hline,ymin=hline),linetype="dashed",color=c("#0072B2","#D55E00"),position=position_dodge())+geom_text(aes(1,meanend-0.4),label=round(meanend,digits=2),size=4,color="#0072B2")+geom_text(aes(2,medianend-0.4),label=round(medianend,digits=2),size=4,color="#D55E00")+xlab("Statistics")+ylab("Value")+theme_bw(base_size = 18,base_family = "")
```

Scenario 4: Constant, then increasing life expectancy

```{r scenario4 36yrs,echo=FALSE}
set.seed(1)
N=500
#every individual was born each year during the 500 years
Year.of.birth<-seq(0,N-1,1)
mean.all<-0
median.all<-0
mean_=mean(survival$Age.at.death)
median_=median(survival$Age.at.death)
meandep=0.5
mediandep=0.5
#simulate that the life expectancy is increasing during the last 21 years(1990-2010)
start=480
end=500
for (i in 1:1000){
#simulate survival time during 500 years
Age.of.death<-weibull_eventtime_stop(mean_,median_,meandep,mediandep,N,start,end)
Year.of.death<-Year.of.birth+Age.of.death
survdata<-data.frame(Year.of.birth,Year.of.death,Age.of.death)
#mean and median survival time of the individuals who died between the 465th year to the 500th year(36years)
mean.all[i]=mean((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])
median.all[i]=median((survdata %>% filter(Year.of.death >= 465, Year.of.death <= 500))[,"Age.of.death"])
}
#boxplot of means and medians
meanend=mean_+meandep*(end-start)
medianend=median_+mediandep*(end-start)
simulation_num<-1:1000
meanmedian=data.frame(mean=mean.all,median=median.all,simulation_num)
df<-melt(meanmedian,c("simulation_num"))
true<-data.frame(variable=c("mean","median"),hline=c(meanend,medianend))
df %>% ggplot(aes(x=variable,y=value))+geom_boxplot() +geom_jitter(alpha=0.1,position = position_jitter(width = 0.3,seed=1))+xlab("mean")+ylab("value")+stat_summary(fun.y = "mean", geom = "point", colour = "#000000", size = 2)+ stat_summary(fun.y="mean", colour="#000000", geom="text", vjust=-0.7,size=4, aes( label=round(..y.., digits=1)))+geom_errorbar(data=true,aes(y=NULL,ymax=hline,ymin=hline),linetype="dashed",color=c("#0072B2","#D55E00"),position=position_dodge())+geom_text(aes(1,meanend-0.4),label=round(meanend,digits=2),size=4,color="#0072B2")+geom_text(aes(2,medianend-0.4),label=round(medianend,digits=2),size=4,color="#D55E00")+xlab("Statistics")+ylab("Value")+theme_bw(base_size = 18,base_family = "")
```