---
title: "scenario_mean_median"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path="../figs/")
```

```{r loadpackage,ehco=FALSE}
library(simsurv)
library(dplyr)
library(ggplot2)
source("weibull_function.R")
```

```{r read data,include=FALSE}
survival<-read.csv("../data/M_Type_A_survival.csv")
```

Scenario 1: Constant life expectancy

```{r constant,echo=FALSE}
meanst=round(mean(survival$Age.at.death),digits=2)
medianst=round(median(survival$Age.at.death),digits=2)
mean=rep(meanst,500)
median=rep(medianst,500)
year=1:500
colors=c("Mean survival time"=c("#0072B2"),"Median survival time"="#D55E00")
df=data.frame(year,mean,median)
df %>% ggplot(aes(year)) + geom_line(aes(y=mean,x=year,color="Mean survival time")) + geom_line(aes(y=median,x=year,color = "Median survival time"),linetype= "dashed")+ylim(0,60)+scale_x_continuous(breaks=c(1,465,500),labels=c("1","465","500"))+scale_color_manual(values = colors)+ylab("Survival")+xlab("Year")+geom_text(aes(label=c("25.3"),x=510,y=mean,color="Mean survival time"),size=6,show.legend=F)+geom_text(aes(label=c("20.8"),x=510,y=median,color="Median survival time"),size=6,show.legend=F)+theme_bw(base_size = 18,base_family = "")+theme(axis.text.x = element_text(angle = 70, hjust = 1, vjust = 0.5),legend.title=element_blank(),legend.position="bottom")+guides(color = guide_legend(override.aes = list(linetype = c("solid", "dashed"))))
```

Senario 2: Gradually increasing life expectancy

```{r increasing500,echo=FALSE}
order=0:499
meandep=0.05
mediandep=0.05
mean=meanst+meandep*order
median=medianst+mediandep*order
year=1:500
colors=c("Mean survival time"="#0072B2","Median survival time"="#D55E00")
df=data.frame(year,mean,median)
df %>% ggplot(aes(year)) + geom_line(aes(y=mean,x=year,color="Mean survival time")) + geom_line(aes(y=median,x=year,color = "Median survival time"),linetype="dashed")+scale_x_continuous(breaks=c(1,465,500),labels=c("0","465","500"))+scale_color_manual(values = colors)+ylab("Survival")+xlab("Year")+geom_text(aes(label=mean[1],x=-1,y=mean[1],color="Mean survival time"),size=6,show.legend=F)+geom_text(aes(label=median[1],x=-1,y=median[1],color="Median survival time"),size=6,show.legend=F)+geom_text(aes(label=mean[500],x=510,y=mean[500],color="Mean survival time"),size=6,show.legend=F)+geom_text(aes(label=median[500],x=510,y=median[500],color="Median survival time"),size=6,show.legend=F)+ylim(0,60)+labs(colour="")+theme_bw(base_size = 18,base_family = "")+theme(axis.text.x = element_text(angle = 70, hjust = 1, vjust = 0.5),legend.title=element_blank(),legend.position ="bottom")+guides(color = guide_legend(override.aes = list(linetype = c("solid", "dashed"))))
```

Scenario 3: Gradually increasing life expectancy that later stabilizes

```{r increasing first 100yrs,echo=FALSE}
order=c(0:459,rep(459,40))
meandep=0.05
mediandep=0.05
mean=meanst+meandep*order
median=medianst+mediandep*order
year=1:500
colors=c("Mean survival time"="#0072B2","Median survival time"="#D55E00")
df=data.frame(year,mean,median)
df %>% ggplot(aes(year)) + geom_line(aes(y=mean,x=year,color="Mean survival time")) + geom_line(aes(y=median,x=year,color = "Median survival time"),linetype="dashed")+scale_x_continuous(breaks=c(1,100,465,480,500),labels=c("1","100","465","480","500"))+scale_color_manual(values = colors)+ylab("Survival")+xlab("Year")+geom_text(aes(label=mean[1],x=-1,y=mean[1],color="Mean survival time"),size=6,show.legend=F)+geom_text(aes(label=median[1],x=-1,y=median[1],color="Median survival time"),size=6,show.legend=F)+geom_text(aes(label=mean[500],x=510,y=mean[500],color="Mean survival time"),size=6,show.legend=F)+geom_text(aes(label=median[500],x=510,y=median[500],color="Median survival time"),size=6,show.legend=F)+ylim(0,60)+theme_bw(base_size = 18,base_family = "")+theme(axis.text.x = element_text(angle = 70, hjust = 1, vjust = 0.5),legend.title=element_blank(),legend.position="bottom")+guides(color = guide_legend(override.aes = list(linetype = c("solid", "dashed"))))
```

Scenario 4: Constant, then increasing life expectancy

```{r increasing last 20yrs,echo=FALSE}
order=c(rep(0,460),1:40)
meandep=0.5
mediandep=0.5
mean=meanst+meandep*order
median=medianst+mediandep*order
year=1:500
colors=c("Mean survival time"="#0072B2","Median survival time"="#D55E00")
df=data.frame(year,mean,median)
df %>% ggplot(aes(year)) + geom_line(aes(y=mean,x=year,color="Mean survival time")) + geom_line(aes(y=median,x=year,color = "Median survival time"),linetype="dashed")+scale_x_continuous(breaks=c(1,465,480,500),labels=c("1","465","480","500"))+scale_color_manual(values = colors)+ylab("Survival")+xlab("Year")+geom_text(aes(label=mean[1],x=-2,y=mean[1],color="Mean survival time"),size=6,show.legend=F)+geom_text(aes(label=median[1],x=-2,y=median[1],color="Median survival time"),size=6,show.legend=F)+geom_text(aes(label=mean[500],x=510,y=mean[500],color="Mean survival time"),size=6,show.legend=F)+geom_text(aes(label=median[500],x=510,y=median[500],color="Median survival time"),size=6,show.legend=F)+ylim(0,60)+theme_bw(base_size = 18,base_family = "")+theme(axis.text.x = element_text(angle = 70, hjust = 1, vjust = 0.5),legend.title=element_blank(),legend.position="bottom")+guides(color = guide_legend(override.aes = list(linetype = c("solid", "dashed"))))
```