---
title: "Table1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadpackage,ehco=FALSE}
library(simsurv)
library(dplyr)
library(ggplot2)
library(reshape)
library(survival)
source("weibull_function.R")
```

```{r read data,include=FALSE}
survival <- read.csv("../data/M_Type_A_survival.csv")
```

Scenario 1: Constant life expectancy

```{r scenario1, echo=FALSE}
set.seed(1)
## Define the number of years for simulation
N <- 500
## Every individual was born each year during the 500 years
Year_of_birth <- seq(1, N, 1)
## Get the mean and median from the dataset
mean_orig <- mean(survival$Age.at.death)
median_orig <- median(survival$Age.at.death)
## Define the increasing rate of mean and median
meandep <- 0
mediandep <- 0
died_mean <- vector()
died_median <- vector()
born_mean <- vector()
born_median <- vector()
for (i in 1:1000){
  ## Simulate survival time during 500 years
  Age_of_death <- weibull_eventtime(mean_orig, median_orig, meandep,
                                    mediandep, N)
  Year_of_death <- Year_of_birth+Age_of_death
  df <- data.frame(Year_of_birth, Year_of_death, Age_of_death)
  ## Died since 465 and before the end of the study
  df1 <- df %>% filter(Year_of_death>=465, Year_of_death<=500)
  ## Born since 465
  df2 <- df %>% filter(Year_of_birth>=465)
  ## Died since Year 465 
  died_mean[i] <- mean(df1$Age_of_death)
  died_median[i] <- median(df1$Age_of_death)
  ##Born since Year 465
  born_mean[i] <- mean(df2$Age_of_death)
  born_median[i] <- median(df2$Age_of_death)
}
list("true.mean"=mean_orig, 
     "estimated.mean.period"=mean(died_mean),
     "std.mean.period"=sd(died_mean),
     "estimated.mean.cohort"=mean(born_mean),
     "std.mean.cohort"=sd(born_mean),
     "true.median"=median_orig,
     "estimated.median.period"=mean(died_median),
     "std.median.period"=sd(born_median),
     "estimated.median.chort"=mean(born_median),
     "std.median.cohort"=sd(born_median))
```

Scenario 2: Gradually increasing life expectancy

```{r scenario2,echo=FALSE}
set.seed(1)
## Define the number of years for simulation
N <- 500
## Every individual was born each year during the 500 years
Year_of_birth <- seq(1, N, 1)
## Get the mean and median from the dataset
mean_orig <- mean(survival$Age.at.death)
median_orig <- median(survival$Age.at.death)
## Define the increasing rate of mean and median
meandep <- 0.05
mediandep <- 0.05
died_mean <- vector()
died_median <- vector()
born_mean <- vector()
born_median <- vector()
for (i in 1:1000){
  ##Simulate survival time during 500 years
  Age_of_death <- weibull_eventtime(mean_orig, median_orig, 
                                    meandep, mediandep, N)
  Year_of_death <- Year_of_birth+Age_of_death
  df <- data.frame(Year_of_birth, Year_of_death, Age_of_death)
  ## Died since 465 and before the end of the study
  df1 <- df %>% filter(Year_of_death>=465, Year_of_death<=500)
  ## Born since 465
  df2 <- df %>% filter(Year_of_birth>=465)
  ## Died since Year 465 
  died_mean[i] <- mean(df1$Age_of_death)
  died_median[i] <- median(df1$Age_of_death)
  ##Born since Year 465
  born_mean[i] <- mean(df2$Age_of_death)
  born_median[i] <- median(df2$Age_of_death)
}
## Calculate the actual mean and median for each year
order <- 0:499
means <- mean_orig+meandep*order
medians <- median_orig+mediandep*order
## Get the average mean and median survival since 465
meanavg <- sum(means[465:500])/length(means[465:500])
medianavg <- sum(medians[465:500])/length(medians[465:500])
list("true.mean"=meanavg, 
     "estimated.mean.period"=mean(died_mean),
     "std.mean.period"=sd(died_mean),
     "estimated.mean.cohort"=mean(born_mean),
     "std.mean.cohort"=sd(born_mean),
     "true.median"=medianavg,
     "estimated.median.period"=mean(died_median),
     "std.median.period"=sd(born_median),
     "estimated.median.chort"=mean(born_median),
     "std.median.cohort"=sd(born_median))
```

Scenario 3: Gradually increasing life expectancy that later stabilizes

```{r KM scenario3,echo=FALSE}
set.seed(1)
## Define the number of years for simulation
N <- 500
## Every individual was born each year during the 500 years
Year_of_birth <- seq(1, N, 1)
## Get the mean and median from the dataset
mean_orig <- mean(survival$Age.at.death)
median_orig <- median(survival$Age.at.death)
## Define the increasing rate of mean and median
meandep <- 0.05
mediandep <- 0.05
died_mean <- vector()
died_median <- vector()
born_mean <- vector()
born_median <- vector()
## Life expectancy rising for the first 460 years and then stabilize
start <- 1
end <- 460
for (i in 1:1000){
  ## Simulate survival time during 500 years
  Age_of_death <- weibull_eventtime_stop(mean_orig, median_orig,
                                       meandep, mediandep, N, 
                                       start, end)
  Year_of_death <- Year_of_birth+Age_of_death
  df <- data.frame(Year_of_birth, Year_of_death, Age_of_death)
  ## Died since 465 and before the end of the study
  df1 <- df %>% filter(Year_of_death>=465, Year_of_death<=500)
  ## Born since 465
  df2 <- df %>% filter(Year_of_birth>=465)
  ## Died since Year 465 
  died_mean[i] <- mean(df1$Age_of_death)
  died_median[i] <- median(df1$Age_of_death)
  ##Born since Year 465
  born_mean[i] <- mean(df2$Age_of_death)
  born_median[i] <- median(df2$Age_of_death)
}
## Calculate the actual mean and median for each year
order <- c(0:(end-1),rep(end-1,500-end))
means <- mean_orig+meandep*order
medians <- median_orig+mediandep*order
## Get the average mean and median survival since 465
meanavg <- sum(means[465:500])/length(means[465:500])
medianavg <- sum(medians[465:500])/length(medians[465:500])
list("true.mean"=meanavg, 
     "estimated.mean.period"=mean(died_mean),
     "std.mean.period"=sd(died_mean),
     "estimated.mean.cohort"=mean(born_mean),
     "std.mean.cohort"=sd(born_mean),
     "true.median"=medianavg,
     "estimated.median.period"=mean(died_median),
     "std.median.period"=sd(born_median),
     "estimated.median.chort"=mean(born_median),
     "std.median.cohort"=sd(born_median))
```
Scenario 4: Constant, then increasing life expectancy

```{r KM scenario4,echo=FALSE}
set.seed(1)
## Define the number of years for simulation
N <- 500
## Every individual was born each year during the 500 years
Year_of_birth <- seq(1, N, 1)
## Get the mean and median from the dataset
mean_orig <- mean(survival$Age.at.death)
median_orig <- median(survival$Age.at.death)
## Define the increasing rate of mean and median
meandep <- 0.5
mediandep <- 0.5
died_mean <- vector()
died_median <- vector()
born_mean <- vector()
born_median <- vector()
## Life expectancy firstly stabilize and then increase since 460
start <- 460
end <- 500
for (i in 1:1000){
  ## Simulate survival time during 500 years
  Age_of_death <- weibull_eventtime_stop(mean_orig, median_orig, 
                                       meandep,mediandep,N,
                                       start,end)
  Year_of_death <- Year_of_birth+Age_of_death
  df <- data.frame(Year_of_birth, Year_of_death, Age_of_death)
  ## Died since 465 and before the end of the study
  df1 <- df %>% filter(Year_of_death>=465, Year_of_death<=500)
  ## Born since 465
  df2 <- df %>% filter(Year_of_birth>=465)
  ## Died since Year 465 
  died_mean[i] <- mean(df1$Age_of_death)
  died_median[i] <- median(df1$Age_of_death)
  ##Born since Year 465
  born_mean[i] <- mean(df2$Age_of_death)
  born_median[i] <- median(df2$Age_of_death)
}
## Calculate the actual mean and median for each year
order <- c(rep(0,start),1:(end-start))
means <- mean_orig+meandep*order
medians <- median_orig+mediandep*order
## Get the average mean and median survival since 465
meanavg <- sum(means[465:500])/length(means[465:500])
medianavg <- sum(medians[465:500])/length(medians[465:500])
list("true.mean"=meanavg, 
     "estimated.mean.period"=mean(died_mean),
     "std.mean.period"=sd(died_mean),
     "estimated.mean.cohort"=mean(born_mean),
     "std.mean.cohort"=sd(born_mean),
     "true.median"=medianavg,
     "estimated.median.period"=mean(died_median),
     "std.median.period"=sd(born_median),
     "estimated.median.chort"=mean(born_median),
     "std.median.cohort"=sd(born_median))
```
